/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventRouteImport } from './routes/$event'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IdcardRouteImport } from './routes/idcard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EventIndexRouteImport } from './routes/$event.index'
import { Route as EventCertificateRouteImport } from './routes/$event.certificate'
import { Route as EventRegisterRouteImport } from './routes/$event.register'
import { Route as EventSuccessRouteImport } from './routes/$event.success'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as VerifyCertRouteImport } from './routes/verify.$cert'
import { Route as EventPartnerSlugRouteImport } from './routes/$event.partner.$slug'
import { Route as CampaignsSlugIndexRouteImport } from './routes/campaigns.$slug.index'
import { Route as CampaignsSlugRegisterRouteImport } from './routes/campaigns.$slug.register'
import { Route as RegisterPartnerSlugRouteImport } from './routes/register.partner.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/$event',
  path: '/$event',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardRoute = IdcardRouteImport.update({
  id: '/idcard',
  path: '/idcard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventRoute,
} as any)
const EventCertificateRoute = EventCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => EventRoute,
} as any)
const EventRegisterRoute = EventRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventRoute,
} as any)
const EventSuccessRoute = EventSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => EventRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertRoute = VerifyCertRouteImport.update({
  id: '/verify/$cert',
  path: '/verify/$cert',
  getParentRoute: () => rootRouteImport,
} as any)
const EventPartnerSlugRoute = EventPartnerSlugRouteImport.update({
  id: '/partner/$slug',
  path: '/partner/$slug',
  getParentRoute: () => EventRoute,
} as any)
const CampaignsSlugIndexRoute = CampaignsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugRegisterRoute = CampaignsSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const RegisterPartnerSlugRoute = RegisterPartnerSlugRouteImport.update({
  id: '/partner/$slug',
  path: '/partner/$slug',
  getParentRoute: () => RegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$event': typeof EventRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/idcard': typeof IdcardRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/$event/certificate': typeof EventCertificateRoute
  '/$event/register': typeof EventRegisterRoute
  '/$event/success': typeof EventSuccessRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/verify/$cert': typeof VerifyCertRoute
  '/$event/': typeof EventIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/$event/partner/$slug': typeof EventPartnerSlugRoute
  '/campaigns/$slug/register': typeof CampaignsSlugRegisterRoute
  '/register/partner/$slug': typeof RegisterPartnerSlugRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/idcard': typeof IdcardRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/$event/certificate': typeof EventCertificateRoute
  '/$event/register': typeof EventRegisterRoute
  '/$event/success': typeof EventSuccessRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/verify/$cert': typeof VerifyCertRoute
  '/$event': typeof EventIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/$event/partner/$slug': typeof EventPartnerSlugRoute
  '/campaigns/$slug/register': typeof CampaignsSlugRegisterRoute
  '/register/partner/$slug': typeof RegisterPartnerSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$event': typeof EventRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/idcard': typeof IdcardRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/$event/certificate': typeof EventCertificateRoute
  '/$event/register': typeof EventRegisterRoute
  '/$event/success': typeof EventSuccessRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/verify/$cert': typeof VerifyCertRoute
  '/$event/': typeof EventIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/$event/partner/$slug': typeof EventPartnerSlugRoute
  '/campaigns/$slug/register': typeof CampaignsSlugRegisterRoute
  '/register/partner/$slug': typeof RegisterPartnerSlugRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$event'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/idcard'
    | '/privacy'
    | '/register'
    | '/success'
    | '/terms'
    | '/$event/certificate'
    | '/$event/register'
    | '/$event/success'
    | '/admin/checkin'
    | '/campaigns/$slug'
    | '/verify/$cert'
    | '/$event/'
    | '/campaigns/'
    | '/$event/partner/$slug'
    | '/campaigns/$slug/register'
    | '/register/partner/$slug'
    | '/campaigns/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/idcard'
    | '/privacy'
    | '/register'
    | '/success'
    | '/terms'
    | '/$event/certificate'
    | '/$event/register'
    | '/$event/success'
    | '/admin/checkin'
    | '/verify/$cert'
    | '/$event'
    | '/campaigns'
    | '/$event/partner/$slug'
    | '/campaigns/$slug/register'
    | '/register/partner/$slug'
    | '/campaigns/$slug'
  id:
    | '__root__'
    | '/'
    | '/$event'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/idcard'
    | '/privacy'
    | '/register'
    | '/success'
    | '/terms'
    | '/$event/certificate'
    | '/$event/register'
    | '/$event/success'
    | '/admin/checkin'
    | '/campaigns/$slug'
    | '/verify/$cert'
    | '/$event/'
    | '/campaigns/'
    | '/$event/partner/$slug'
    | '/campaigns/$slug/register'
    | '/register/partner/$slug'
    | '/campaigns/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventRoute: typeof EventRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  ContactRoute: typeof ContactRoute
  IdcardRoute: typeof IdcardRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  VerifyCertRoute: typeof VerifyCertRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$event': {
      id: '/$event'
      path: '/$event'
      fullPath: '/$event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard': {
      id: '/idcard'
      path: '/idcard'
      fullPath: '/idcard'
      preLoaderRoute: typeof IdcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$event/': {
      id: '/$event/'
      path: '/'
      fullPath: '/$event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof EventRoute
    }
    '/$event/certificate': {
      id: '/$event/certificate'
      path: '/certificate'
      fullPath: '/$event/certificate'
      preLoaderRoute: typeof EventCertificateRouteImport
      parentRoute: typeof EventRoute
    }
    '/$event/register': {
      id: '/$event/register'
      path: '/register'
      fullPath: '/$event/register'
      preLoaderRoute: typeof EventRegisterRouteImport
      parentRoute: typeof EventRoute
    }
    '/$event/success': {
      id: '/$event/success'
      path: '/success'
      fullPath: '/$event/success'
      preLoaderRoute: typeof EventSuccessRouteImport
      parentRoute: typeof EventRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$cert': {
      id: '/verify/$cert'
      path: '/verify/$cert'
      fullPath: '/verify/$cert'
      preLoaderRoute: typeof VerifyCertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$event/partner/$slug': {
      id: '/$event/partner/$slug'
      path: '/partner/$slug'
      fullPath: '/$event/partner/$slug'
      preLoaderRoute: typeof EventPartnerSlugRouteImport
      parentRoute: typeof EventRoute
    }
    '/campaigns/$slug/': {
      id: '/campaigns/$slug/'
      path: '/'
      fullPath: '/campaigns/$slug/'
      preLoaderRoute: typeof CampaignsSlugIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/register': {
      id: '/campaigns/$slug/register'
      path: '/register'
      fullPath: '/campaigns/$slug/register'
      preLoaderRoute: typeof CampaignsSlugRegisterRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/register/partner/$slug': {
      id: '/register/partner/$slug'
      path: '/partner/$slug'
      fullPath: '/register/partner/$slug'
      preLoaderRoute: typeof RegisterPartnerSlugRouteImport
      parentRoute: typeof RegisterRoute
    }
  }
}

interface EventRouteChildren {
  EventCertificateRoute: typeof EventCertificateRoute
  EventRegisterRoute: typeof EventRegisterRoute
  EventSuccessRoute: typeof EventSuccessRoute
  EventIndexRoute: typeof EventIndexRoute
  EventPartnerSlugRoute: typeof EventPartnerSlugRoute
}

const EventRouteChildren: EventRouteChildren = {
  EventCertificateRoute: EventCertificateRoute,
  EventRegisterRoute: EventRegisterRoute,
  EventSuccessRoute: EventSuccessRoute,
  EventIndexRoute: EventIndexRoute,
  EventPartnerSlugRoute: EventPartnerSlugRoute,
}

const EventRouteWithChildren = EventRoute._addFileChildren(EventRouteChildren)

interface AdminRouteChildren {
  AdminCheckinRoute: typeof AdminCheckinRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCheckinRoute: AdminCheckinRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RegisterRouteChildren {
  RegisterPartnerSlugRoute: typeof RegisterPartnerSlugRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterPartnerSlugRoute: RegisterPartnerSlugRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface CampaignsSlugRouteChildren {
  CampaignsSlugRegisterRoute: typeof CampaignsSlugRegisterRoute
  CampaignsSlugIndexRoute: typeof CampaignsSlugIndexRoute
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugRegisterRoute: CampaignsSlugRegisterRoute,
  CampaignsSlugIndexRoute: CampaignsSlugIndexRoute,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventRoute: EventRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CertificateRoute: CertificateRoute,
  ContactRoute: ContactRoute,
  IdcardRoute: IdcardRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  VerifyCertRoute: VerifyCertRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
